Default: &defaults
  database: TalkAllocator.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: TalkAllocator_test.sqlite3
  <<: *defaults

Staging:
  database: TalkAllocator_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: TalkAllocator_production.sqlite3
  poolsize: 100
  <<: *defaults
